### ISSUE TITLE
Dagather 협업 관련 이슈

### ISSUE THREAD

**Issue by KimKwon** [Dagather/Dagather-Front#2]
Git
===========
[GitKraken](https://www.gitkraken.com/) 을 사용하도록 하겠습니다.

[Repo Link](https://github.com/Dagather/Dagather-Front) URL 복사해서 클론하여서 사용하시면 됩니다.

Dagather Branch 관리
====================
협업 효율성의 향상을 위한 브랜치 관리 전략입니다.

Branch Convention 
----------------------------
1. 기능 구현 시 개별적으로 브랜치를 생성하여 작업합니다.
2. 추가 기능 개발 시 ```feature/<개발기능 이름>``` 과 같이 생성합니다.
3. 브랜치의 모든 이름은 snake case를 사용해서 네이밍합니다.

```
작성 예시

* feature
 - request
 - robot-screen
 - user-screen
* fix
 - splash-screen
```
- - -
Pull Request
-------------
<img width="165" alt="스크린샷 2021-01-29 오후 7 09 47" src="https://user-images.githubusercontent.com/22493971/106261963-a1c20c80-6265-11eb-8207-2935c05ce783.png">
<img width="538" alt="스크린샷 2021-01-29 오후 7 09 59" src="https://user-images.githubusercontent.com/22493971/106261965-a25aa300-6265-11eb-9ba7-5505a91af85c.png">

해당 기능의 개발을 완료하였다면, Pull Request를 생성해야합니다.
위와 같은 과정으로 이루어지며, PR 올렸다고 따로 언급해주시면 다른 인원의 빠른 확인이 가능합니다.

또한, Pull Request가 Merge 되기 위해서는 팀원 1명의 Approve가 필요하도록 설정하겠습니다.

## Approve Rule

**반드시 코드를 읽어보셔야합니다.**

변경 사항에 대해 코드를 리뷰합니다.
작성자가 발견하지 못한 실수나, 이슈, 에러를 발견할 수도 있기 때문에 꼭 해야합니다. 

실수를 발견했으면 코멘트를 달아 수정을 요구하거나, 문제사항에 대해 언급해주시면 됩니다.

## Issue 작성

1. 혼자 해결하기 힘든 에러 발생 혹은 기존 코드에서 에러/오류 발견 시 작성해주시면 됩니다...
2. 그 외에도 본인이 공부한 내용을 정리해서 업로드하셔도 됩니다.
3. 이 부분은 특별한 양식 없이 Label만 어느정도 신경써서 작성해주시면 됩니다.

- - -
Dagather Coding Convention
=====================
사람마다 모두 코딩 컨벤션이 다르기 때문에, 코드의 통일성을 제공하기 위함입니다.

ESLint & Prettier
-----
Airbnb ESLint 룰을 사용할 것이고, 설정 완료시켜서 커밋하겠습니다.
룰에 대한 추가적인 협의는 개발 진행하면서 맞춰보겠습니다.

VSCode Extension
-----------
<img width="218" alt="스크린샷 2021-01-29 오후 7 58 06" src="https://user-images.githubusercontent.com/22493971/106266995-66770c00-626c-11eb-80cf-77752140e15d.png">
<img width="214" alt="스크린샷 2021-01-29 오후 7 58 09" src="https://user-images.githubusercontent.com/22493971/106266998-67a83900-626c-11eb-9d2a-33726c0dc735.png">
<img width="216" alt="스크린샷 2021-01-29 오후 7 58 12" src="https://user-images.githubusercontent.com/22493971/106267000-6840cf80-626c-11eb-9dfe-6635cb69d290.png">
<img width="221" alt="스크린샷 2021-01-29 오후 7 58 22" src="https://user-images.githubusercontent.com/22493971/106267003-6840cf80-626c-11eb-8d10-d56db2719965.png">

저는 이렇게 사용하고 있습니다.
- - -

**Comment by jekyun-park** [comment]
Goooooood
